name: GoldIsMoney
main: com.flobi.GoldIsMoney.GoldIsMoney
version: 1.dev

commands:
  vt:
    description: Test Vauls 
    usage: |
           /<command> deposit [playerName] [amount] - Deposit
           /<command> withdraw [playerName] [amount] - Withdraw
           /<command> balance [playerName] - Balance
  vault-convert:
    description: Converts all data in economy1 and dumps it into economy2
    usage: |
           /<command> [economy1] [economy2]
