name: GoldIsMoney
main: com.flobi.GoldIsMoney.GoldIsMoney
version: 1.1.2

description: Economy driven by inventory gold.
author: flobi
website: http://dev.bukkit.org/server-mods/goldismoney/

database: false

permissions:
  goldismoney.use:
    description: Allow gold to be money.
    default: true
